### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by devstra** [devstra/crypto-cost-avg#1]
- [ ] Add support for other coins
- [ ] Add ability to choose start date
- [ ] Add posibility of having an initial investment
- [ ] Add proper error handling
- [ ] Add support for bi-weekly investing
